
# ============================================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# ============================================================

# SauceDemo Production URL
application.url=https://www.saucedemo.com/


# Environment name
environment.name=prod
